# El projectKey debe ser EXACTAMENTE este o el proyecto no aparece listado en SonarQube
sonar.projectKey=Sebastian_Hernandez_t1
sonar.projectName=Sebastian_Hernandez_t1

sonar.sources=.
sonar.exclusions=.venv/**, **/tests/**, utils/**
sonar.host.url=https://sonarqube.ingsoftware.lat/
sonar.token=sqa_4e296de25b56b315988b9a9dfd137d2b4f97e7c3

# Pruebas y cobertura
sonar.tests=tests
sonar.test.inclusions=**/tests/**, **test_*.py
sonar.python.coverage.reportPaths=coverage.xml
