#Cambiar el project key por el nombre_apellido_t1
#Poner las exclusiones de codigo que sean necesarias (Las mismas de un git ignore de python, ts, java, etc)
#Incluir la info de donde se ubican sus test y su archivo de cobertura

sonar.projectKey=Fabrizzio_Vilchez_t1
sonar.sources=.
sonar.exclusions=.venv/**, **/tests/**
sonar.host.url=https://sonarqube.ingsoftware.lat/
sonar.token=sqa_4e296de25b56b315988b9a9dfd137d2b4f97e7c3

# CONFIGURACIÓN DE PRUEBAS Y COBERTURA
sonar.tests=.
sonar.test.inclusions=**/tests/**, **test_*.py
sonar.python.coverage.reportPaths=coverage.xml